# Generated by Django 5.1.1 on 2024-10-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='position_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
